# Generated by Django 4.2.3 on 2024-03-19 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала привычки'),
        ),
    ]
